### ISSUE TITLE
Ignore duplicate KeyboardInput events

### ISSUE THREAD

**Issue by parasyte** [rukai/winit_input_helper#17]
I haven't looked into this too much, but at least on Windows 11, winit sends repeated `KeyboardInput` events while a key is held. These repeated events will always push `KeyAction::Pressed(_)`, causing `key_pressed()` to return true at the same interval as the repeat events.

https://github.com/rukai/winit_input_helper/blob/106e033c718ccfb346866c054d23025666ae13ae/src/current_input.rs#L54-L60

IMHO, this code should only push the `KeyAction` when `self.key_held[keycode as usize] == false` (i.e. the key has not been released since the last pressed event).

**Comment by rukai** [comment]
The current implementation is working as designed, it obeys the OS's key repeat implementation.
For my use case of building an in game editor (actual gameplay was on gamepads only) this was exactly what I wanted.

But I can see that for gameplay this would not be ideal, if you have an action key that is activated on key press then you dont want that action to repeat if the key is held down.

Currently we have 3 key functions:
* key_pressed
* key_released
* key_held

In order for the user to get the desired functionality they would need to keep record of the state from previous frames, and given that this library is pretty high level I think it makes sense to do that for them.

So I'm proposing that we have 4 key functions:
* key_pressed # new functionality that you proposed.
* key_pressed_os # same functionality as old key_pressed
* key_released
* key_held

In order to do this we will have to take the small performance hit of keeping another key_actions vec around, but I cant see a better solution.

**Comment by parasyte** [comment]
The doc for `key_pressed` seems to indicate the repeat events are unexpected. But I agree with the overall sentiment; repeat events are very useful in UIs.

**Comment by rukai** [comment]
I've implemented it here: https://github.com/rukai/winit_input_helper/commit/2ce7b79bc6f6e3a91556690790b09f468cd0487d
Unless you have any further issues i'll release 0.12 tomorrow.

**Comment by parasyte** [comment]
> I've implemented it here: [2ce7b79](https://github.com/rukai/winit_input_helper/commit/2ce7b79bc6f6e3a91556690790b09f468cd0487d) Unless you have any further issues i'll release 0.12 tomorrow.

Can confirm, this works wonderfully for games!

**Comment by rukai** [comment]
Released 0.12
