### ISSUE TITLE
A way to trigger on chorded input? (e.g. `C-x q`)

### ISSUE THREAD

**Issue by rirze** [rukai/winit_input_helper#38]
Hi,

I like how this crate simplifies a lot of the logic in winit's input matching system-- was wondering if this crate had a way to trigger on chorded key commands (`CTRL-X` and then followed by another letter like `Q`). 

I'm a little new to rust and the ecosystem, but if this is not currently possible, I was thinking of creating some sort of queue that tracks key combinations being pressed and trigger based on that. Do you think that would work or/and be a performant technique? 

Any insight would be appreciated!

**Comment by rukai** [comment]
winit_input_helper is focused towards games and small demos, where chorded inputs arent needed.

If winit_input_helper were to support chorded inputs I imagine the API would look like this:
```rust
/// Return the last 10 combined inputs
fn chorded_input(&self, &[Vec<VirtualKeyCode>]) { }

/// and then it would be used like
if helper.chorded_input(&[vec!(VirtualKeyCode::Control, VirtualKeyCode::X), vec!(VirtualKeyCode::Q)]) {
   // do thing
}
```

But I suspect that if you need chorded inputs for your application then your application is going to have complex enough input needs that you should be using winit directly instead of winit_input_helper.

So I think chorded inputs should be done in the application code, or maybe in a winit_input_helper like crate that is more specific to the needs of your application.

What sort of application are you building that needs chorded inputs?

**Comment by rirze** [comment]
Ah, I didn't realize winit_input_helper was geared towards games and demos-- I was looking at it as a possible crate for handling keyboard shortcuts for my editor application.

Specifically something like in emacs, where you have mode maps (like `CTRL-X`) and that opens up an entire different layer of shortcuts. 

Since opening this issue, I've found [inlyne's implemenation](https://github.com/trimental/inlyne/tree/main/src/keybindings) of the same concept. I've been using an edited version of that module for now.

But I suspect this will all change a bit as winit's new keyboard input system releases and I'll have to update my code then.

**Comment by rukai** [comment]
Yeah, my thinking for gui applications (including text editors) being out of scope for winit_input_helper is that for implementing a gui application you should always be using a gui framework like egui or iced or something that abstracts away winit.
Such frameworks will not want to use winit_input_helper and instead want complete control over the way they process winit events.

> Since opening this issue, I've found [inlyne's implemenation](https://github.com/trimental/inlyne/tree/main/src/keybindings) of the same concept. I've been using an edited version of that module for now.

I'm glad to hear you've found an approach that works for you.

I'll go ahead and close this issue now.
